title: Sillycation
description: A web application for groups of friends to collect, vote on, and rank memorable moments from their trip
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
    values:
      layout: default
